markdown: kramdown
baseurl: bassi.li
exclude: ['README.md', vendor]
version: 0.1.0

username:             FlatlanderWoman
repo:                 FlatlanderWoman.github.io
branch:               master

title:                Michael Bassili
url:                  http://bassi.li
author:               Michael Bassili
description:          Michael Bassili pursues programming projects, writes words about stuff, and drinks coffee while listening to music. He also likes video games, I think.

source:               .
destination:          _site

gems:
  - jekyll-feed
