markdown:             kramdown
baseurl:              https://bassi.li
exclude:              ['README.md', vendor]
version:              0.3.4

username:             FlatlanderWoman
repo:                 FlatlanderWoman.github.io
branch:               master

title:                Michael Bassili
author:               Michael Bassili
url:                  https://bassi.li
description:          Michael Bassili pursues side projects, writes words about stuff, and drinks coffee while listening to music. He also likes video games, I think.

source:               .
destination:          _site

plugins:
  - jekyll-feed

jekyll_admin:
  hidden_links:
    - datafiles
