markdown:             kramdown
exclude:              ['README.md', vendor]
version:              1.0.1

username:             FlatlanderWoman
repo:                 FlatlanderWoman.github.io
branch:               master

title:                Michael Bassili
author:               Michael Bassili
url:                  https://bassi.li
description:          TODO

source:               .
destination:          _site

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

jekyll_admin:
  hidden_links:
    - datafiles
