markdown:             kramdown
exclude:              ['README.md', vendor]
version:              1.0.2

paginate:             1

username:             FlatlanderWoman
repo:                 FlatlanderWoman.github.io
branch:               master

title:                Michael Bassili
author:               Michael Bassili
url:                  https://bassi.li
description:          Michael Bassili is a remote programmer and side-project advocate.

source:               .
destination:          _site

plugins:
  - jekyll-feed
  - jekyll-sitemap

jekyll_admin:
  hidden_links:
    - datafiles
