markdown:    kramdown
exclude:     ['README.md', vendor]
version:     1.0.1
username:    FlatlanderWoman
repo:        FlatlanderWoman.github.io
branch:      master
title:       Michael Bassili
author:      Michael Bassili
url:         https://bassi.li
description: My name is Michael Bassili, and I am a programmer. I also do other things, many of which are not conventionally productive or helpful to my career. Moreover, I really like those productivity self-help books you can find in the Business section of Chapters—I especially like it when authors of said productivity self-help books talk about themselves like they’re the Productivity Messiah, or something.
source:      .
destination: _site
highlighter: rouge
linenos:     true

gems:
  - jekyll-feed
  - jekyll-sitemap

jekyll_admin:
  hidden_links:
    - datafiles

highlight:
  linenos: true

highlight_options:
  linenos: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
